### ISSUE TITLE
Bug, websocket error

### ISSUE THREAD

**Issue by piotrkochan** [inf3cti0n95/Rocket.Chat.RealTime.API.RxJS#23]
There is an error

```
/node_modules/rxjs/observable/dom/WebSocketSubject.js:39
    throw new Error('no WebSocket constructor can be found');
```

**Comment by inf3cti0n95** [comment]
Can you provide in what environment are you using this?, I believe RxJS cannot find the WebSocket constructor from the global scope.

**Comment by inf3cti0n95** [comment]
Closed, inactive issue. Reopen if problem still persists.
