### ISSUE TITLE
[Question] Method for closing websocket connection

### ISSUE THREAD

**Issue by kawin-impekable** [inf3cti0n95/Rocket.Chat.RealTime.API.RxJS#24]
Is there a way to disconnect the websocket from Rocket.Chat ? if I understand it correctly there is no way to access `this.webSocket` from outside the lib. `this.getObservable().unsubscribe()` won't work either I guess because it returns `this.webSocket.catch()`. If this is true what about having new method for disconnecting the socket like this ? If it looks okay I can make a merge request for it

    public disconnect() {
        return this.webSocket.unsubscribe();
    }

**Comment by inf3cti0n95** [comment]
Oh yes! I didn't think of disconnecting the websocket, You should send me a PR with an appropriate documentation, I'll merge it. Thanks a bunch !
