### ISSUE TITLE
[Bug] `obj is undefined` error on login

### ISSUE THREAD

**Issue by kawin-impekable** [inf3cti0n95/Rocket.Chat.RealTime.API.RxJS#30]
If Websocket Connection is terminated before `getLoginObservable` function is executed this error will be thrown

<img width="1076" alt="screen shot 2561-06-21 at 12 42 57 am" src="https://user-images.githubusercontent.com/32444803/41675285-7901f616-74ec-11e8-96ed-32c710fb4a09.png">

The problem is in this line 
`https://github.com/inf3cti0n95/Rocket.Chat.RealTime.API.RxJS/blob/master/src/RealTimeAPI.ts#L176`

If I understand it correctly, when Websocket is terminated and there is no response that match the `find` operator. The `.map(obj => obj[0])` statement at the end of the line will throw out this error.

So my proposed fix is to add the condition to check if `obj` exist to resolve this issue.

**Comment by kawin-impekable** [comment]
@inf3cti0n95 I've created a PR to fix this but I'm not sure if it's the best approach to go. Please take a look when you have a free time :)

**Comment by inf3cti0n95** [comment]
Can you tell way to recreate this bug?

**Comment by kawin-impekable** [comment]
What I did is `connectToServer` and then using any `login` method (All of them going to call `getLoginObservable` anyway) then terminate the WebSocket right away. This error will occur.

I think it related to #21 , in his case he called `login` before `connectToServer` so there is no response back from RealTime API and cause `getLoginObservable` to throw the error.

**Comment by inf3cti0n95** [comment]
I am still not getting, can you post the code to recreate it please. I'll review it and try to comeback to so asap.

**Comment by kawin-impekable** [comment]
sure, but it's late night here. I'll try to create a code to reproduce this tomorrow!

**Comment by kawin-impekable** [comment]
@inf3cti0n95 try this https://github.com/kawin-impekable/react-rocket-chat-sample

**Comment by inf3cti0n95** [comment]
@kawin-impekable Sorry for being inactive. I studied the issue, the code I had written was too imperative, Could you please see the last fix that I have made. Does that solve the issue you had?

**Comment by inf3cti0n95** [comment]
Closed, Issue fixed and released.
